services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: wallet-live-db
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: